// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proge.Teams.Edu.DAL;

#nullable disable

namespace Proge.Teams.Edu.DAL.Migrations
{
    [DbContext(typeof(TeamsEduDbContext))]
    partial class UniMoReDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0-rc.2.21480.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Proge.Teams.Edu.DAL.Entities.CallRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CallDescription")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("EndDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("JoinWebUrl")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Modalities")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("StartDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("JoinWebUrl");

                    b.HasIndex("Type");

                    b.ToTable("CallRecord");
                });

            modelBuilder.Entity("Proge.Teams.Edu.DAL.Entities.CallSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CallSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CallUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CallUserRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("EndDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("StartDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserPlatform")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserProductFamily")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CallSessionId");

                    b.HasIndex("Id");

                    b.ToTable("CallSessionSegment");
                });

            modelBuilder.Entity("Proge.Teams.Edu.DAL.Entities.CallSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CallRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CallUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CallUserRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("EndDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("StartDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserPlatform")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserProductFamily")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CallRecordId");

                    b.HasIndex("CallUserId");

                    b.HasIndex("Id");

                    b.ToTable("CallSession");
                });

            modelBuilder.Entity("Proge.Teams.Edu.DAL.Entities.CallUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserRole")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("CallRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<Guid?>("UserTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id", "UserRole", "CallRecordId");

                    b.HasIndex("CallRecordId");

                    b.HasIndex("DisplayName");

                    b.HasIndex("UserRole");

                    b.ToTable("CallUser");
                });

            modelBuilder.Entity("Proge.Teams.Edu.DAL.Entities.ChangeNotification", b =>
                {
                    b.Property<Guid?>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ODataId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChangeType")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ODataType")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("RawJson")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resource")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTimeOffset?>("SubscriptionExpirationDateTime")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id", "ODataId", "ChangeType");

                    b.HasIndex("ChangeType");

                    b.ToTable("ChangeNotification");
                });

            modelBuilder.Entity("Proge.Teams.Edu.DAL.Entities.ExamTeamsRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalDataString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("App_appelloId")
                        .HasColumnType("bigint");

                    b.Property<string>("App_cdsCod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("App_cdsDes")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<long?>("App_cdsId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("App_dataFineIscr")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("App_dataInizioApp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("App_dataInizioIscr")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ArchivedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DipCod")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ins_aa_offerta")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ins_aa_ord")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ins_ad_cod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ins_cds_cod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ins_pds_cod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("InternalId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMembershipLimitedToOwners")
                        .HasColumnType("bit");

                    b.Property<bool?>("MailSent")
                        .HasColumnType("bit");

                    b.Property<string>("Members")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owners")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TeamCreated")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("TeamCreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TeamId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TeamJoinUrl")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("TeamRequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TeamRequestUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TeamRequested")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExamTeamsRequest");
                });

            modelBuilder.Entity("Proge.Teams.Edu.DAL.Entities.LatestLog", b =>
                {
                    b.Property<string>("Exception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("TimeStamp")
                        .HasColumnType("datetimeoffset");

                    b.ToView("LatestLog");
                });

            modelBuilder.Entity("Proge.Teams.Edu.DAL.Entities.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Exception")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("LogEvent")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageTemplate")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Properties")
                        .HasColumnType("xml");

                    b.Property<DateTimeOffset>("TimeStamp")
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("Level");

                    b.HasIndex("TimeStamp");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Proge.Teams.Edu.DAL.Entities.Member", b =>
                {
                    b.Property<Guid>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Mail")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("OfficeLocation")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserPrincipalName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MemberId");

                    b.HasIndex("UserPrincipalName");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Proge.Teams.Edu.DAL.Entities.Team", b =>
                {
                    b.Property<Guid>("TeamsId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdCod")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("AdDesc")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AdId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AdditionalDataString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnnoOfferta")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("AnnoOrdinamento")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("CdsCod")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InternalId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMembershipLimitedToOwners")
                        .HasColumnType("bit");

                    b.Property<string>("JoinCode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("JoinUrl")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TeamType")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TeamsId");

                    b.HasIndex("ExternalId");

                    b.HasIndex("TeamType");

                    b.HasIndex("TeamsId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Proge.Teams.Edu.DAL.Entities.TeamMember", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MemberType")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TeamId", "MemberId", "MemberType");

                    b.HasIndex("MemberId");

                    b.HasIndex("MemberType");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("Proge.Teams.Edu.DAL.Entities.TeamsMeeting", b =>
                {
                    b.Property<string>("JoinUrl")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Attendees")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChatMessageId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ChatThreadId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomAttribute")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeetingExtendedAttribute")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MeetingExtendedName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MeetingHierarchy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MeetingId")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("MeetingIdPrimary")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MeetingIdSecondary")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MeetingName")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MeetingType")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OwnerExtended")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OwnerUpn")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("JoinUrl");

                    b.HasIndex("MeetingId");

                    b.ToTable("TeamsMeeting");
                });

            modelBuilder.Entity("Proge.Teams.Edu.DAL.Entities.TeamWithMemeber", b =>
                {
                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InternalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMembershipLimitedToOwners")
                        .HasColumnType("bit");

                    b.Property<string>("JoinCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JoinUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MemberType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TeamsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserPrincipalName")
                        .HasColumnType("nvarchar(max)");

                    b.ToView("TeamsWithMemeber");
                });

            modelBuilder.Entity("Proge.Teams.Edu.DAL.Entities.CallSegment", b =>
                {
                    b.HasOne("Proge.Teams.Edu.DAL.Entities.CallSession", "CallSession")
                        .WithMany("CallSegments")
                        .HasForeignKey("CallSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CallSession");
                });

            modelBuilder.Entity("Proge.Teams.Edu.DAL.Entities.CallSession", b =>
                {
                    b.HasOne("Proge.Teams.Edu.DAL.Entities.CallRecord", "CallRecord")
                        .WithMany("CallSessions")
                        .HasForeignKey("CallRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CallRecord");
                });

            modelBuilder.Entity("Proge.Teams.Edu.DAL.Entities.CallUser", b =>
                {
                    b.HasOne("Proge.Teams.Edu.DAL.Entities.CallRecord", "CallRecord")
                        .WithMany("CallUsers")
                        .HasForeignKey("CallRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CallRecord");
                });

            modelBuilder.Entity("Proge.Teams.Edu.DAL.Entities.TeamMember", b =>
                {
                    b.HasOne("Proge.Teams.Edu.DAL.Entities.Member", "Member")
                        .WithMany("TeamsUsers")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proge.Teams.Edu.DAL.Entities.Team", "Team")
                        .WithMany("TeamsUsers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Proge.Teams.Edu.DAL.Entities.CallRecord", b =>
                {
                    b.Navigation("CallSessions");

                    b.Navigation("CallUsers");
                });

            modelBuilder.Entity("Proge.Teams.Edu.DAL.Entities.CallSession", b =>
                {
                    b.Navigation("CallSegments");
                });

            modelBuilder.Entity("Proge.Teams.Edu.DAL.Entities.Member", b =>
                {
                    b.Navigation("TeamsUsers");
                });

            modelBuilder.Entity("Proge.Teams.Edu.DAL.Entities.Team", b =>
                {
                    b.Navigation("TeamsUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
